apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: task-api
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default

  selector:
    matchLabels:
      app: task-api

  endpoints:
    - port: http
      path: /metrics
      interval: 15s